### ISSUE TITLE
PHP 7.2 and 7.3 fails to download because the downloads.php.net url has uppercase VC15 instead of lowercase

### ISSUE THREAD

**Issue by TysonAndre** [php/setup-php-sdk#10] opened 2024-08-10 17:51 UTC
https://downloads.php.net/~windows/releases/archives/ has the list of files that currently exist
Exists on the web server: https://downloads.php.net/~windows/releases/archives/php-7.3.33-nts-Win32-VC15-x64.zip
What setup-php-sdk attempted to download: https://downloads.php.net/~windows/releases/archives/php-7.3.33-nts-Win32-vc15-x64.zip (VC15 vs lowercase vc15)

Same for https://downloads.php.net/~windows/releases/archives/php-7.2.34-nts-Win32-vc15-x64.zip having vc15 while the actual download URL is VC15)

- Maybe the web server used to work because it used to served URLs case insensitively due to a case insensitive filesystem?

Possible solutions:
1. Change the web server config (would not recommend unless this is a widespread new cause of failures to download for many different files, which seems unlikely)
2. Add alternate filenames to the web server
3. Work around this in run.ps1

The invalid urls were hardcoded in run1.ps ($vs is `vc15` for php 7.3)

```sh
$temp = New-TemporaryFile | Rename-Item -NewName {$_.Name + ".zip"} -PassThru
$fname = "php-$phpversion-$tspart-$vs-$arch.zip"
$url = "$baseurl/$fname"
Write-Output "Downloading $url ..."
Invoke-WebRequest $url -OutFile $temp
Expand-Archive $temp "php-bin"
```

https://github.com/igbinary/igbinary/actions/runs/10333358916/job/28605611621?pr=392 failed for php 7.2 and 7.3

```
Run D:\a\_actions\php\setup-php-sdk\v0.9/run -version 7.2 -arch x64 -ts nts -deps @()
Install PHP SDK ...
Install PHP 7.2.34 ...
Downloading https://downloads.php.net/~windows/releases/archives/php-7.2.34-nts-Win32-vc15-x64.zip ...
Invoke-WebRequest : Not Found
The requested URL was not found on this server.
At D:\a\_actions\php\setup-php-sdk\v0.9\run.ps1:90 char:1
```

```
Run D:\a\_actions\php\setup-php-sdk\v0.9/run -version 7.3 -arch x64 -ts nts -deps @()
Install PHP SDK ...
Install PHP 7.3.33 ...
Downloading https://downloads.php.net/~windows/releases/archives/php-7.3.33-nts-Win32-vc15-x64.zip ...
Invoke-WebRequest : Not Found
The requested URL was not found on this server.
At D:\a\_actions\php\setup-php-sdk\v0.9\run.ps1:90 char:1
```

**Comment by cmb69** [comment] 2024-08-10 18:19
> * Maybe the web server used to work because it used to served URLs case insensitively due to a case insensitive file?

Indeed, the server at window.php.net is IIS on Windows. downloads.php.net is Apache on Linux.

> Work around this in run.ps1

That might be the most viable solution, but still, just changing the hard-coded values is unlikely to work, since these are used elsewhere too.

@shivammathur, any suggestion on how to handle this? Is https://github.com/php/php-windows-builder also affected by this?

**Comment by shivammathur** [comment] 2024-08-10 18:56
@cmb69 
Yes, I accounted for that in php-windows-builder [here](https://github.com/php/php-windows-builder/blob/master/extension/BuildPhpExtension/private/Get-PhpBuild.ps1#L36).

Work around for this can be added here in run.ps1, a better solution would be to configure apache to be case insensitive for archives directory so that existing use cases everywhere continue to work.

**Comment by derickr** [comment] 2024-08-10 19:17
I don't really want to add hacks to the apache configuration for this. Is this a common pattern we can rewrite with a Permanently Moved header?

**Comment by cmb69** [comment] 2024-08-11 09:54
> Is this a common pattern we can rewrite with a Permanently Moved header?

Which use cases should be addressed? If it is only about the Github actions, setup-php-sdk could use what php-windows-builder is already doing (thanks @shivammathur!); clients would need to update to the new version, though. If it is about the most general case, such rewrite rules may get ugly; e.g. `windows.php.net/downloads/RELEASES/PHP-7.4.33-NTS-win32-vc15-X64.ZIP` works (and some may even use weirder URLs), while that obviously wouldn't work for a case sensitive file system. And using external redirects (e.g. 301) would break scripts which don't handle redirects.

**Comment by TysonAndre** [comment] 2024-08-11 17:56
Releasing a new version of setup-php-sdk special casing 7.2 and 7.3 in the powershell downloading script would be fine with me

**Comment by derickr** [comment] 2024-08-12 16:10
I've fixed this on the server now — it does a redirect

**Comment by cmb69** [comment] 2024-08-15 15:48
> I've fixed this on the server now — it does a redirect

I can confirm that this works, so we can close this ticket.

**Closed as completed by cmb69** 2024-08-15 15:48 UTC
Labels: bug
